version: '3.8'
volumes:
  mariadbv:
services:
  mariadb:
    image: gyoon/mariadb
    container_name: gyoon-mariadb
    build: ./requirements/mariadb/.
    volumes:
      - "mariadbv:/var/lib/mysql"
    env_file:
      - .env
    expose:
      - "3306"
    restart: always