services:
  nginx:
    image: gyoon/nginx
    container_name: gyoon-nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  
  wordpress:
    image: gyoon/wordpress
    container_name: gyoon-wordpress
    build: ./requirements/wordpress/.
    expose:
      - "9000"
    networks:
      - inception
    restart: always

  mariadb:
    image: gyoon/mariadb
    container_name: gyoon-mariadb
    build: ./requirements/mariadb/.
    expose:
      - "3306"
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

# volumes:
#   wordpress:
#     name: wordpress
    