ARG RELEASE=bullseye

FROM debian:${RELEASE}

COPY ./tools/script.sh /

RUN apt-get update -y \
	&& apt-get upgrade -y \
	&& apt-get install -y \
	php-fpm \
	curl \
	&& sh /script.sh

WORKDIR /var/www/html

ENTRYPOINT ["php", "-S", "localhost:9000" ]

# EXPOSE 9000