ARG RELEASE=bullseye

FROM debian:${RELEASE}

COPY ./tools/script.sh /

RUN	apt-get update -y \
	&& apt-get upgrade -y \
	&& apt-get install -y \
	nginx \
	openssl \
	curl \
	&& sh /script.sh

ENTRYPOINT ["nginx", "-g", "daemon off;"]

EXPOSE 443